language: php

php:
  - 7.1

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - sudo redis-server /etc/redis/redis.conf --port 6380 --requirepass 'secret'
  - npm install npm@latest -g
  - npm install

script:
  - vendor/bin/phpunit --coverage-text
  - npm run production

cache:
  directories:
    - node_modules
    - vendor
