version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/app/circleci/hyungseok/
permissions:
  - object: /home/ubuntu/app/circleci/hyungseok/storage
    mode: 777
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root

