version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/app/codeship/hyungseok/
permissions:
  - object: /home/ubuntu/app/codeship/hyungseok/storage
    mode: 777
    type:
      - directory
  - object: /home/ubuntu/app/codeship/hyungseok/public
    mode: 777
    type:
      - directory
hooks:
  AfterInstall:
    - location: scripts/execute-deploy.sh
      timeout: 300
      runas: root
