version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/app/codeship/hyungseok/

hooks:
  AfterInstall:
    - location: ./scripts/change_permissions.sh
      timeout: 300
      runas: root
