version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/app/codeship/hyungseok/
permissions:
  - object: /home/ubuntu/app/codeship/hyungseok/storage
    mode: 777
    type:
      - directory
hooks:
  ValidateService:
    - location: scripts/restart-codedeploy-agent.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
