version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./hyungseok.template:/etc/nginx/conf.d/hyungseok.template
    ports:
      - '80:80'
      - '443:443'
    environment:
      NGINX_HOST: localhost hyungseok.kr *.hyungseok.kr
      NGINX_PORT: 80
    command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/hyungseok.kr.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  phpfpm:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    expose:
      - 9000
    working_dir: /app/public
