version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/app
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/fastcgi_params:/etc/nginx/fastcgi_params
    expose:
      - '8000'
    environment:
      LETSENCRYPT_HOST: hyungseok.kr,www.hyungseok.kr,api.hyungseok.kr,m.hyungseok.kr
      VIRTUAL_HOST: hyungseok.kr,www.hyungseok.kr,api.hyungseok.kr,m.hyungseok.kr
      VIRTUAL_PORT: 8000
    command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /app/etc/hyungseok.template > /etc/nginx/conf.d/hyungseok.kr.conf && nginx -g 'daemon off;'"
    depends_on:
      - phpfpm
      - redis

  phpfpm:
    image: jhs851/php-7.3-fpm:0.1
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "php artisan clear-compiled && php artisan optimize && php artisan migrate --force && cd public && php-fpm"

  redis:
    image: redis:latest
    volumes:
      - ./etc/redis.conf:/redis.conf
    ports:
      - '6379:6379'
    command: redis-server /redis.conf

networks:
  default:
    external:
      name: proxy
