version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/app
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/fastcgi_params:/etc/nginx/fastcgi_params
      - /etc/letsencrypt/live/hyungseok.kr-0001/fullchain.pem:/etc/letsencrypt/fullchain.pem
      - /etc/letsencrypt/live/hyungseok.kr-0001/privkey.pem:/etc/letsencrypt/privkey.pem
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
    ports:
      - '80:80'
      - '443:443'
    environment:
      NGINX_HOST: 52.78.217.23 hyungseok.kr www.hyungseok.kr api.hyungseok.kr m.hyungseok.kr
      NGINX_PORT: 80
    command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /app/etc/hyungseok_ssl.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  phpfpm:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "php artisan clear-compiled && php artisan optimize && php artisan migrate --force && cd public && php-fpm"

  redis:
    image: redis:latest
    volumes:
      - ./etc/redis.conf:/redis.conf
    ports:
      - '6379:6379'
    command: redis-server /redis.conf

#  composer:
#    image: composer:latest
#    volumes:
#      - ./:/app
#    working_dir: /app
#    command: sh -c "composer update && composer dump-autoload"
#
#  node:
#    image: node:latest
#    volumes:
#      - ./:/app
#    working_dir: /app
#    command: sh -c "rm -rf ./node_modules && rm package-lock.json && npm install && npm run production"
