version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/app
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/fastcgi_params:/etc/nginx/fastcgi_params
    ports:
      - '80:80'
      - '443:443'
    environment:
      NGINX_HOST: localhost hyungseok.kr *.hyungseok.kr
      NGINX_PORT: 80
    command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /app/etc/hyungseok.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  phpfpm:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    working_dir: /app/public

  redis:
    image: redis:latest
    volumes:
      - ./etc/redis.conf:/redis.conf
    ports:
      - '6379:6379'
    command: redis-server /redis.conf
