version: '3'

services:
  nginx:
    restart: always
    container_name: hyungseok-nginx
    image: nginx:alpine
    volumes:
      - ./:/app
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/fastcgi_params:/etc/nginx/fastcgi_params
      - ./etc/hyungseok.kr.template:/etc/nginx/conf.d/hyungseok.kr.conf
    environment:
      LETSENCRYPT_HOST: hyungseok.kr,www.hyungseok.kr,api.hyungseok.kr,m.hyungseok.kr
      VIRTUAL_HOST: hyungseok.kr,www.hyungseok.kr,api.hyungseok.kr,m.hyungseok.kr
    depends_on:
      - phpfpm
      - redis
    networks:
      - default
      - proxy

  phpfpm:
    restart: always
    container_name: hyungseok-phpfpm
    image: jhs851/php-7.3-fpm:0.1
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "php artisan clear-compiled && php artisan optimize && php artisan migrate --force && cd public && php-fpm"

  redis:
    restart: always
    container_name: redis
    image: redis:latest
    volumes:
      - ./etc/redis.conf:/redis.conf
    ports:
      - '6379:6379'
    command: redis-server /redis.conf

networks:
  proxy:
    external: true
