# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.4
  aws-code-deploy: circleci/aws-code-deploy@2.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/php:7.4.14-browsers
      - image: cimg/redis:6.2.6
    steps:
      - browser-tools/install-browser-tools:
          # TODO remove following line when fixed https://github.com/CircleCI-Public/browser-tools-orb/issues/90
          chrome-version: 116.0.5845.96

      - checkout

      - run:
          name: "Create Environment file"
          command: |
            mv .env.testing .env

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: "Generate App key"
          command: php artisan key:generate

      - run:
          name: "Install Sqlite"
          command: sudo apt-get install php7.4-sqlite3

      - run:
          name: "Create database and run migration"
          command: |
            touch database/database.sqlite
            php artisan migrate --env=testing

      # run tests with phpunit
      - run:
          name: "Run Unit Tests"
          command: ./vendor/bin/phpunit

workflows:
  build-and-test-deploy-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                master
      - aws-code-deploy/deploy:
          requires:
            - build-and-test
          application-name: hyungseok
          bundle-bucket: hyungseoks-deploy2
          deployment-group: hyungseok-deploy
          bundle-key: hyungseok-zip
          service-role-arn: hyungseok
          filters:
            branches:
              only:
                master
